// Ethiopian Events, Festivals & Travel Blog Data

export interface EthiopianEvent {
  id: string;
  title: string;
  date: string;           // YYYY-MM-DD
  endDate?: string;
  ethiopianDate?: string; // e.g. "Tir 11 (ጥር ፲፩)"
  location: string;
  region: string;
  latitude?: number;
  longitude?: number;
  category: 'religious' | 'cultural' | 'nature' | 'music' | 'food' | 'sport';
  description: string;
  imageUrl: string;
  isFeatured: boolean;
  tipForVisitors?: string;
  dressCode?: string;
  relatedTourTitle?: string;
  relatedTourSlug?: string;
}

export interface BlogArticle {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  content: string;        // simplified, multi-paragraph
  author: string;
  authorAvatar: string;
  publishedAt: string;
  readMinutes: number;
  coverImage: string;
  tags: string[];
  category: 'itinerary' | 'tips' | 'culture' | 'nature' | 'food' | 'guide';
}

export const ETHIOPIAN_REGIONS = [
  'Oromia',
  'Finfinnee (Addis Ababa)',
  'Amhara',
  'Tigray',
  'Sidama',
  'Harari',
  'Afar',
  'Southern Ethiopia',
  'Central Ethiopia',
  'South West Ethiopia',
  'Somali',
  'Benishangul-Gumuz',
  'Gambela',
  'Dire Dawa',
  'Nationwide',
] as const;

export const ETHIOPIAN_EVENTS: EthiopianEvent[] = [
  {
    id: 'evt-1',
    title: 'Timkat – Ethiopian Epiphany',
    date: '2027-01-19',
    endDate: '2027-01-20',
    ethiopianDate: 'Tir 11 (ጥር ፲፩)',
    location: 'Fasilides Bath (Gondar) & Rock Churches (Lalibela)',
    region: 'Amhara',
    latitude: 12.6074,
    longitude: 37.4674,
    category: 'religious',
    description: 'The most spectacular Ethiopian Orthodox festival celebrating Christ\'s baptism. Colorfully robed priests carry ornate tabots (Ark of the Covenant replicas) in grand processions to historic water baths (Fasilides Bath), followed by joyous mass baptism ceremonies at dawn.',
    imageUrl: 'https://images.unsplash.com/photo-1609137144813-7d9921338f24?auto=format&fit=crop&q=80&w=1000',
    isFeatured: true,
    tipForVisitors: 'Arrive 2 days early in Gondar or Lalibela to secure a vantage spot. Dress respectfully in white traditional attire.',
    dressCode: 'White traditional cotton Shema / Netela scarf covering shoulders and head in churches.',
    relatedTourTitle: 'Lalibela Rock-Hewn Churches Pilgrimage',
    relatedTourSlug: 'lalibela-rock-churches-pilgrimage',
  },
  {
    id: 'evt-2',
    title: 'Meskel – Demera Finding of the True Cross',
    date: '2026-09-27',
    endDate: '2026-09-28',
    ethiopianDate: 'Meskerem 17 (መስከረም ፲፯)',
    location: 'Meskel Square, Addis Ababa (Finfinnee)',
    region: 'Addis Ababa (Finfinnee)',
    latitude: 9.0106,
    longitude: 38.7613,
    category: 'religious',
    description: 'UNESCO-inscribed celebration marking the discovery of the True Cross by Queen Helena. Features the ceremonial lighting of the towering conical Demera bonfire as hundreds of thousands chant in unison at sunset in central Addis Ababa.',
    imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&q=80&w=1000',
    isFeatured: true,
    tipForVisitors: 'The Demera bonfire lighting at sunset on September 27 is the peak spectacle — arrive by 3:00 PM at Meskel Square.',
    dressCode: 'Smart casual or traditional Ethiopian white attire.',
    relatedTourTitle: 'Addis Ababa City Highlights & Cultural Odyssey',
    relatedTourSlug: 'addis-ababa-city-highlights-odyssey',
  },
  {
    id: 'evt-3a',
    title: 'Irreecha Malkaa Finfinnee – Oromo Thanksgiving',
    date: '2026-10-03',
    ethiopianDate: 'Meskerem 23 (መስከረም ፳፫)',
    location: 'Hora Finfinnee (Near Meskel Square & ECA), Finfinnee',
    region: 'Addis Ababa (Finfinnee)',
    latitude: 9.0135,
    longitude: 38.7650,
    category: 'cultural',
    description: 'The historic urban Irreecha celebration held at the heart of Finfinnee (Addis Ababa). Millions of Oromo pilgrims from across Oromia and the diaspora gather in vibrant traditional attire at Hora Finfinnee to dip wet green grass into the water, give thanks to Waaqa (God), and welcome the blossoming spring season.',
    imageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&q=80&w=1000',
    isFeatured: true,
    tipForVisitors: 'Head to Hora Finfinnee early morning (6:30 AM). Join the welcoming circle and carry green wet grass (Coqorsa) as a peaceful blessing gesture.',
    dressCode: 'Traditional colorful Oromo attire (Wande / Hariye / Qomee) or white cultural clothes.',
    relatedTourTitle: 'Addis Ababa City Highlights & Cultural Odyssey',
    relatedTourSlug: 'addis-ababa-city-highlights-odyssey',
  },
  {
    id: 'evt-3b',
    title: 'Irreecha Malkaa Arsedi – Grand Lake Thanksgiving',
    date: '2026-10-04',
    ethiopianDate: 'Meskerem 24 (መስከረም ፳፬)',
    location: 'Lake Hora Arsedi, Bishoftu (Debre Zeit)',
    region: 'Oromia',
    latitude: 8.7522,
    longitude: 38.9833,
    category: 'cultural',
    description: 'The colossal climax of Irreecha thanksgiving celebrated at the sacred volcanic Lake Hora Arsedi in Bishoftu. Abbaa Gadaas (Gadaa leaders) and Haadha Siinqees lead sacred prayers of gratitude at the lakefront with horses, singing, and Adey Abeba flowers.',
    imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&q=80&w=1000',
    isFeatured: true,
    tipForVisitors: 'Arrive in Bishoftu the night before. The lakeside fills before dawn with traditional chants and blessing ceremonies.',
    dressCode: 'Traditional Oromo cultural dress with yellow Adey Abeba flowers.',
    relatedTourTitle: 'Wenchi Crater Lake Eco-Resort Expedition',
    relatedTourSlug: 'wenchi-crater-lake-expedition',
  },
  {
    id: 'evt-4',
    title: 'Ashenda / Shadey / Solel Festival of Women',
    date: '2026-08-22',
    endDate: '2026-08-26',
    ethiopianDate: 'Nehase 16–20 (ነሐሴ ፲፮–፳)',
    location: 'Mekelle, Axum & Lalibela',
    region: 'Tigray',
    latitude: 13.4967,
    longitude: 39.4753,
    category: 'cultural',
    description: 'A vibrant, colorful UNESCO-celebrated northern festival dedicated to girls and young women. Women dress in Tilfi embroidered dresses, braid intricate Albaso hairstyles, and tie green Ashenda sedge grass around their waists, singing and drumming through city streets.',
    imageUrl: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&q=80&w=1000',
    isFeatured: true,
    tipForVisitors: 'Mekelle and Axum offer the most energetic street parades where visitors are warmly welcomed to join dancing rings.',
    dressCode: 'Traditional Tilfi embroidered white dress with green grass fringe.',
    relatedTourTitle: 'Lalibela Rock-Hewn Churches Pilgrimage',
    relatedTourSlug: 'lalibela-rock-churches-pilgrimage',
  },
  {
    id: 'evt-5',
    title: 'Fichee-Chambalaalla – Sidama New Year Festival',
    date: '2026-06-25',
    endDate: '2026-06-27',
    ethiopianDate: 'Sene 18 (ሰኔ ፲፰)',
    location: 'Gudumaale Sacred Ground, Hawassa',
    region: 'Sidama',
    latitude: 7.0621,
    longitude: 38.4764,
    category: 'cultural',
    description: 'UNESCO Intangible Cultural Heritage celebrated by the Sidama people. Astrologers (Ayanto) determine the precise date from lunar cycles, followed by communal gatherings at Gudumaale in Hawassa, sharing traditional Bursame dish, and energetic Qetta dancing.',
    imageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&q=80&w=1000',
    isFeatured: true,
    tipForVisitors: 'Hawassa lakefront hotels provide great access to the Gudumaale cultural grounds.',
    dressCode: 'Traditional Sidama woven cotton costume.',
    relatedTourTitle: 'Bale Mountains Ethiopian Wolf Safari',
    relatedTourSlug: 'bale-mountains-ethiopian-wolf-safari',
  },
  {
    id: 'evt-6',
    title: 'Shawal Eid & Jugol Cultural Festival',
    date: '2027-04-10',
    endDate: '2027-04-12',
    ethiopianDate: 'Miyazya 2 (ሚያዝያ ፪)',
    location: 'Harar Jugol Historic Walled City',
    region: 'Harari',
    latitude: 9.3139,
    longitude: 42.1333,
    category: 'cultural',
    description: 'A distinct three-day festival celebrated inside the ancient walled city of Harar immediately following the six days of voluntary Shawwal fasting. Features traditional Harari wedding dances, colorful attire, and nocturnal hyena ceremonies.',
    imageUrl: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&q=80&w=1000',
    isFeatured: false,
    tipForVisitors: 'Walk through the 5 historic gates of Jugol during nighttime music and poetry sessions.',
    dressCode: 'Modest attire respecting Harari Islamic heritage; women wear colorful shawls.',
    relatedTourTitle: 'Harar Jugol Historic City Experience',
    relatedTourSlug: 'harar-jugol-historic-city-hyena-experience',
  },
  {
    id: 'evt-7',
    title: 'Hamar Bull Jumping Rite of Passage (Ukuli Bula)',
    date: '2026-11-15',
    ethiopianDate: 'Hidar 6 (ኅዳር ፮)',
    location: 'Turmi & Dimeka, Lower Omo Valley',
    region: 'Southern Ethiopia',
    latitude: 4.9667,
    longitude: 36.4833,
    category: 'cultural',
    description: 'An ancient rite of passage ceremony where young Hamar men run across the backs of castrated bulls four times to prove their manhood and gain permission to marry, surrounded by Evangadi nighttime dancing.',
    imageUrl: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&q=80&w=1000',
    isFeatured: false,
    tipForVisitors: 'Must be visited with an experienced local community guide with photo permissions.',
    dressCode: 'Safari trekking clothes with sun protection.',
    relatedTourTitle: 'Bale Mountains Ethiopian Wolf Safari',
    relatedTourSlug: 'bale-mountains-ethiopian-wolf-safari',
  },
  {
    id: 'evt-8',
    title: 'Dallol & Erta Ale Salt Caravan Gathering',
    date: '2026-12-10',
    ethiopianDate: 'Tahsas 1 (ታኅሣሥ ፩)',
    location: 'Lake Karum (Assale) & Dallol, Afar Depression',
    region: 'Afar',
    latitude: 14.2417,
    longitude: 40.2986,
    category: 'nature',
    description: 'Gathering of hundreds of traditional camel salt caravans across the blinding white salt flats of Lake Karum in Afar, where miners extract salt slabs using ancient hand tools beneath glowing volcanic horizons.',
    imageUrl: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&q=80&w=1000',
    isFeatured: false,
    tipForVisitors: 'Wear UV-blocking sunglasses, lightweight long-sleeve cotton, and sturdy desert hiking boots.',
    dressCode: 'Desert breathable expedition clothing.',
    relatedTourTitle: 'Danakil Depression & Erta Ale Expedition',
    relatedTourSlug: 'danakil-depression-erta-ale',
  },
  {
    id: 'evt-9',
    title: 'Gurage Meskel & Enset Harvest Celebration',
    date: '2026-09-26',
    endDate: '2026-09-30',
    ethiopianDate: 'Meskerem 16–20 (መስከረም ፲፮–፳)',
    location: 'Welkite & Butajira',
    region: 'Central Ethiopia',
    latitude: 8.2833,
    longitude: 37.7833,
    category: 'cultural',
    description: 'The Gurage cultural homecoming festival where hundreds of thousands travel from across Ethiopia back to their ancestral highlands for week-long feasts of Kitfo, Kocho, and traditional dance rituals.',
    imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&q=80&w=1000',
    isFeatured: false,
    tipForVisitors: 'A prime opportunity to taste authentic highland spiced butter Kitfo and organic Kocho bread.',
    dressCode: 'Traditional Gurage cultural attire or smart casual.',
    relatedTourTitle: 'Wenchi Crater Lake Eco-Resort Expedition',
    relatedTourSlug: 'wenchi-crater-lake-expedition',
  },
  {
    id: 'evt-10',
    title: 'Kaffa Wild Rainforest Coffee Origin Festival',
    date: '2026-12-05',
    ethiopianDate: 'Hidar 26 (ኅዳር ፳፮)',
    location: 'Bonga & Harenna Forest',
    region: 'South West Ethiopia',
    latitude: 7.2833,
    longitude: 36.2333,
    category: 'food',
    description: 'Held in the birthplace of Arabica coffee (Kaffa Biosphere Reserve). Local forest communities demonstrate ancient harvesting of wild canopy coffee beans followed by authentic multi-round Bunna brewing ceremonies.',
    imageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&q=80&w=1000',
    isFeatured: false,
    tipForVisitors: 'Participate in coffee cupping and eco-trekking in the virgin rainforest canopy.',
    dressCode: 'Light rainforest trekking attire with waterproof hiking boots.',
    relatedTourTitle: 'Bale Mountains Ethiopian Wolf Safari',
    relatedTourSlug: 'bale-mountains-ethiopian-wolf-safari',
  },
  {
    id: 'evt-11',
    title: 'Great Ethiopian Run (10k International Road Race)',
    date: '2026-11-22',
    ethiopianDate: 'Hidar 13 (ኅዳር ፲፫)',
    location: 'Meskel Square & Bole Rd, Finfinnee',
    region: 'Addis Ababa (Finfinnee)',
    latitude: 9.0106,
    longitude: 38.7613,
    category: 'sport',
    description: 'Africa\'s largest road race founded by Olympic champion Haile Gebrselassie. Over 45,000 international and local runners take over the high-altitude streets of Finfinnee (Addis Ababa) in an electrifying street carnival.',
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=1000',
    isFeatured: false,
    tipForVisitors: 'Acclimatize to the 2,400m altitude at least 2 days prior to race day.',
    dressCode: 'Official race t-shirt & running shoes.',
    relatedTourTitle: 'Addis Ababa City Highlights & Cultural Odyssey',
    relatedTourSlug: 'addis-ababa-city-highlights-odyssey',
  },
  {
    id: 'evt-12',
    title: 'Enkutatash – Ethiopian New Year Celebration',
    date: '2026-09-11',
    ethiopianDate: 'Meskerem 1 (መስከረም ፩, 2019 E.C.)',
    location: 'Addis Ababa (Finfinnee) & Nationwide',
    region: 'Nationwide',
    latitude: 9.0300,
    longitude: 38.7400,
    category: 'cultural',
    description: 'Celebrates the arrival of spring sunshine after 3 months of rainy season. Children sing traditional songs with yellow Adey Abeba daisies while families feast on Doro Wot and freshly brewed Ethiopian coffee.',
    imageUrl: 'https://images.unsplash.com/photo-1609137144813-7d9921338f24?auto=format&fit=crop&q=80&w=1000',
    isFeatured: false,
    tipForVisitors: 'Experience joyous greeting rituals and traditional hospitalities in local restaurants.',
    dressCode: 'Festive cultural clothes with yellow flower accessories.',
    relatedTourTitle: 'Addis Ababa City Highlights & Cultural Odyssey',
    relatedTourSlug: 'addis-ababa-city-highlights-odyssey',
  },
];

export const BLOG_ARTICLES: BlogArticle[] = [
  {
    id: 'blog-1',
    slug: 'ultimate-lalibela-pilgrimage-guide',
    title: 'The Ultimate Lalibela Pilgrimage Guide: Rock Churches, Routes & Reverence',
    excerpt: 'Carved from solid basalt rock in the 12th century, Lalibela\'s 11 monolithic churches are one of humanity\'s greatest architectural achievements. Here\'s everything you need to plan an unforgettable visit.',
    content: `Lalibela sits at 2,630 metres in the Lasta mountains of Amhara, a medieval city whose entire reason for existence is sacred. King Lalibela commissioned 11 churches hewn directly from red volcanic rock — not built on top, but carved downward and inward, creating subterranean cathedrals connected by tunnels and trenches.\n\nThe Northwestern Cluster contains Bet Medhane Alem, the world\'s largest monolithic church, supported by 36 exterior pillars. Nearby, the intimate Bet Maryam houses remarkable 12th-century frescoes.\n\nThe Southeastern Cluster includes the most famous of all: Bet Giyorgis (St George), a perfectly cruciform church carved in isolation down a steep rocky pit. Its geometric roof, etched with interlocking crosses, is visible from above before you descend the winding path.\n\nVisit during Gena (Ethiopian Christmas in January) or Fasika (Orthodox Easter) for unforgettable midnight masses with thousands of white-robed pilgrims holding candles in the ancient tunnels.`,
    author: 'Tigist Haile',
    authorAvatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&q=80&w=100',
    publishedAt: '2026-07-15',
    readMinutes: 8,
    coverImage: 'https://images.unsplash.com/photo-1609137144813-7d9921338f24?auto=format&fit=crop&q=80&w=1200',
    tags: ['Lalibela', 'UNESCO', 'Rock Churches', 'Pilgrimage', 'Amhara'],
    category: 'guide',
  },
  {
    id: 'blog-2',
    slug: 'danakil-depression-survival-guide',
    title: 'Danakil Depression Survival Guide: Earth\'s Hottest Inhabited Place',
    excerpt: 'At 116 metres below sea level, the Danakil is one of the most extreme environments on the planet. Neon sulphur springs, active lava lakes, and ancient salt caravans await — if you\'re prepared.',
    content: `The Danakil Depression in Ethiopia\'s Afar Region is routinely measured as the hottest permanently inhabited place on Earth, with average annual temperatures of 34–35°C and spikes well above 50°C. It is also one of the most geologically active zones on the planet.\n\nDallol hydrothermal field — a surreal landscape of neon yellow, green, and orange sulphur pools, salt chimneys, and acid brine channels — looks like another planet. The colours come from extreme chemistry: pH levels near zero, temperatures above boiling.\n\nErta Ale is one of only five lava lakes in the world with a permanently active lava lake in its summit caldera. The night trek (2–4 hours each way across dark lava plains) rewards with an incandescent glow visible from kilometres away.\n\nAfaris of the salt caravans: Ancient Afar tribes still extract pure white salt slabs from the ancient dried lake bed using traditional hand tools, loading camel trains that walk for days to highland markets — unchanged for centuries.`,
    author: 'Mohammed Ahmed',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=100',
    publishedAt: '2026-08-01',
    readMinutes: 10,
    coverImage: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&q=80&w=1200',
    tags: ['Danakil', 'Erta Ale', 'Dallol', 'Afar', 'Extreme Travel'],
    category: 'guide',
  },
  {
    id: 'blog-3',
    slug: '7-day-ethiopian-highlands-itinerary',
    title: '7-Day Ethiopian Highlands Itinerary: Simien, Wenchi & Gondar',
    excerpt: 'A week is just enough time to experience the dramatic escarpments of the Simien Mountains, the volcanic paradise of Wenchi Crater Lake, and the medieval castles of Gondar. Here\'s the perfect itinerary.',
    content: `Day 1–2: Fly into Gondar. Spend the first afternoon at Fasil Ghebbi — the Royal Enclosure of 17th-century stone castles built by Emperor Fasilides. Day 2 visit the Debre Birhan Selassie church, whose ceiling is covered in painted angel faces.\n\nDay 3–5: Drive to Debark (3 hours) and enter the Simien Mountains National Park. Hike from Sankaber to Geech camp, passing vertical cliff drops of over 1,000m. The Gelada baboon troops are the highlight — enormous social families of golden-maned primates grazing in full view on mountain meadows.\n\nDay 6: Return to Addis Ababa by evening flight. Day 7: Day trip west from Addis to Wenchi Crater Lake (2.5 hours). Motorboat across to the island monastery, soak in volcanic hot springs, horseback ride along the crater rim — all in one day before returning to Addis for a final farewell coffee ceremony.`,
    author: 'Abebe Bekele',
    authorAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=100',
    publishedAt: '2026-07-28',
    readMinutes: 7,
    coverImage: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=1200',
    tags: ['Itinerary', 'Simien Mountains', 'Wenchi', 'Gondar', '7 Days'],
    category: 'itinerary',
  },
  {
    id: 'blog-4',
    slug: 'ethiopian-coffee-culture-guide',
    title: 'Ethiopian Coffee Culture: The Birthplace of Arabica',
    excerpt: 'Ethiopia is the birthplace of coffee. From wild Harenna forest plants to the elaborate three-round coffee ceremony, understanding Ethiopian coffee culture makes every cup more meaningful.',
    content: `The coffee plant (Coffea arabica) originated in the highlands of Ethiopia\'s Kaffa region — a fact preserved in the word "coffee" itself, derived from "Kaffa." Wild arabica trees still grow naturally in the Harenna Forest of Bale Mountains at 1,500–2,400 metres altitude.\n\nThe Ethiopian coffee ceremony (Bunna) is a 45–60 minute ritual performed three times daily in many homes. Green beans are washed and roasted over charcoal in front of guests, ground in a mortar, brewed in a clay jebena pot, and served in small ceramic cups (sini) with sugar, salt, or butter depending on the region.\n\nThree rounds are traditional: Abol (first, strongest), Tona (second, medium), and Baraka (third, "blessing"). Refusing any of the three rounds is considered impolite.\n\nHarar is home to some of Ethiopia\'s most distinctive coffee: small, dry-processed beans with wine-like, mocha notes grown on ancient terraced farms inside the walled city. Look for Harar Longberry coffee in the city market.`,
    author: 'Tigist Haile',
    authorAvatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&q=80&w=100',
    publishedAt: '2026-06-20',
    readMinutes: 6,
    coverImage: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&q=80&w=1200',
    tags: ['Coffee', 'Culture', 'Harar', 'Bale', 'Ceremony'],
    category: 'culture',
  },
  {
    id: 'blog-5',
    slug: 'best-time-to-visit-ethiopia',
    title: 'Best Time to Visit Ethiopia: Month-by-Month Season Guide',
    excerpt: 'Ethiopia has two distinct seasons — dry and rainy — and knowing when to go is the difference between a muddy trail and a pristine highland trek. Here\'s a practical month-by-month breakdown.',
    content: `Ethiopia uses the Ge\'ez calendar with 13 months. The country straddles the equator but most highlands have a moderate climate year-round.\n\nOctober to February (Dry Season / Birr): The absolute best time to travel. Post-Meskel landscapes are lush and golden, wildlife is abundant, and hiking conditions are excellent. Timkat in January draws massive, colourful crowds.\n\nMarch to May (Short Rains / Belg): The south and lowlands get short rains. Still good for the north — Lalibela, Gondar, and Simien stay accessible. Wildflowers bloom on mountain slopes.\n\nJune to September (Main Rainy Season / Kiremt): Heavy rains in the highlands. Simien trails can be muddy and some roads become challenging. However, the landscape turns spectacularly green and waterfalls are at their most powerful — perfect for waterfall photography. Danakil remains accessible year-round (but even hotter in summer).`,
    author: 'Abebe Bekele',
    authorAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=100',
    publishedAt: '2026-05-10',
    readMinutes: 5,
    coverImage: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&q=80&w=1200',
    tags: ['Season', 'Travel Tips', 'Weather', 'Planning', 'Best Time'],
    category: 'tips',
  },
];
