import type { TourPackage, Destination } from '@/types/tour';
import type { Booking } from '@/types/booking';
import type { TourGuide } from '@/types/guide';
import type { MetricCardData } from '@/types/common';

export const INITIAL_TOURISM_METRICS: MetricCardData[] = [
  {
    id: 'm1',
    title: 'Total Booking Revenue',
    value: 'ETB 18,450,000',
    changePercent: 22.4,
    changeType: 'positive',
    description: 'vs. previous month',
    iconName: 'DollarSign',
  },
  {
    id: 'm2',
    title: 'Active Expeditions',
    value: '36',
    changePercent: 12.5,
    changeType: 'positive',
    description: 'En-route across Ethiopian tourist circuits',
    iconName: 'Compass',
  },
  {
    id: 'm3',
    title: 'Booked Travelers',
    value: '640',
    changePercent: 18.2,
    changeType: 'positive',
    description: 'Domestic & International tourists',
    iconName: 'Users',
  },
  {
    id: 'm4',
    title: 'Satisfaction Rating',
    value: '4.96 / 5.0',
    changePercent: 3.5,
    changeType: 'positive',
    description: 'Based on 850+ verified traveler reviews',
    iconName: 'Star',
  },
];

export const DESTINATIONS: Destination[] = [
  {
    id: 'dest-1',
    name: 'Wenchi Crater Lake',
    country: 'Ethiopia',
    region: 'Oromia Region',
    imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&q=80&w=1000',
    description: 'Breathtaking volcanic crater lake surrounded by lush alpine greenery, hot mineral thermal springs, waterfall trails, and island monasteries.',
  },
  {
    id: 'dest-2',
    name: 'Lalibela Rock Churches',
    country: 'Ethiopia',
    region: 'Amhara Region',
    imageUrl: 'https://images.unsplash.com/photo-1609137144813-7d9921338f24?auto=format&fit=crop&q=80&w=1000',
    description: 'World-famous UNESCO World Heritage site boasting 11 monolithic churches carved directly out of solid red basalt rock in the 12th century.',
  },
  {
    id: 'dest-3',
    name: 'Simien Mountains National Park',
    country: 'Ethiopia',
    region: 'Gonder / Amhara',
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=1000',
    description: 'Dramatic serrated mountain escarpments, deep precipitous gorges, endemic Gelada baboon troops, and Ras Dashen peak.',
  },
  {
    id: 'dest-4',
    name: 'Danakil Depression & Erta Ale',
    country: 'Ethiopia',
    region: 'Afar Region',
    imageUrl: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&q=80&w=1000',
    description: 'One of the lowest and hottest places on Earth featuring glowing neon Dallol salt springs, traditional salt miners caravans, and active lava lakes.',
  },
  {
    id: 'dest-5',
    name: 'Bale Mountains National Park',
    country: 'Ethiopia',
    region: 'Bale / Oromia',
    imageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&q=80&w=1000',
    description: 'Highland alpine plateau, pristine Harenna cloud forest, endemic Ethiopian wolf sanctuary, and natural Sof Omar limestone caves.',
  },
  {
    id: 'dest-6',
    name: 'Harar Walled Historic City',
    country: 'Ethiopia',
    region: 'Harari Region',
    imageUrl: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&q=80&w=1000',
    description: 'Historic 16th-century UNESCO walled city Jugol with 82 mosques, colorful alleyways, and the world-renowned nighttime wild hyena feeding ritual.',
  },
];

export const INITIAL_TOUR_PACKAGES: TourPackage[] = [
  {
    id: 'tour-101',
    title: 'Wenchi Crater Lake Eco-Resort & Equestrian Expedition',
    slug: 'wenchi-crater-lake-expedition',
    category: 'luxury',
    destination: DESTINATIONS[0],
    pricePerPerson: 450,
    durationDays: 3,
    maxGroupSize: 12,
    difficulty: 'easy',
    rating: 4.98,
    reviewCount: 215,
    imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&q=80&w=1000',
    galleryImages: [
      'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=1000',
    ],
    summary: 'Discover the natural paradise of Wenchi Crater Lake with private motorboat rides to Kirkos Monastery, mineral hot springs, horseback ridge trails, and luxury eco-lodge dining.',
    included: ['Luxury Wenchi Eco-Lodge Stay', 'Private Island Boat Transfers', 'Guided Horseback Ridge Tour', 'Thermal Spring Spa Bathing', 'Traditional Organic Oromo Cuisine'],
    excluded: ['Personal Souvenirs', 'Alcoholic Beverages'],
    itinerary: [
      { dayNumber: 1, title: 'Scenic Drive from Addis Ababa & Lodge Check-in', description: 'Depart Addis via Ambo road, taking in wheat fields and highland mountain views before checking into Wenchi Eco-Lodge.', mealsIncluded: ['Lunch', 'Dinner'], accommodation: 'Wenchi Lakeside Eco-Lodge' },
      { dayNumber: 2, title: 'Lake Boat Cruise, Cherkos Monastery & Thermal Baths', description: 'Board traditional motorboat to the 13th-century Cherkos island monastery followed by a dip in natural volcanic hot springs.', mealsIncluded: ['Breakfast', 'Lunch', 'Dinner'], accommodation: 'Wenchi Lakeside Eco-Lodge' },
      { dayNumber: 3, title: 'Crater Ridge Horseback Trek & Farewell Feast', description: 'Morning guided equestrian trail ride along the crater rim overlooking waterfalls before afternoon return to Addis Ababa.', mealsIncluded: ['Breakfast', 'Lunch'], accommodation: 'N/A' },
    ],
    isFeatured: true,
    status: 'active',
    hasOffer: true,
    discountPercent: 15,
    originalPrice: 530,
    offerTag: '15% OFF SEASONAL PROMO',
  },
  {
    id: 'tour-102',
    title: 'Lalibela World Heritage Monolithic Rock Churches Pilgrimage',
    slug: 'lalibela-rock-churches-pilgrimage',
    category: 'cultural',
    destination: DESTINATIONS[1],
    pricePerPerson: 850,
    durationDays: 4,
    maxGroupSize: 10,
    difficulty: 'moderate',
    rating: 4.96,
    reviewCount: 310,
    imageUrl: 'https://images.unsplash.com/photo-1609137144813-7d9921338f24?auto=format&fit=crop&q=80&w=1000',
    galleryImages: [
      'https://images.unsplash.com/photo-1609137144813-7d9921338f24?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&q=80&w=1000',
    ],
    summary: 'Step back into 12th-century history to marvel at the 11 rock-hewn monolithic churches of King Lalibela, including the iconic cruciform Church of St. George (Bet Giyorgis).',
    included: ['4-Star Mountain View Hotel in Lalibela', 'All UNESCO Church Entrance Passports', 'Official Certified Heritage Historian Guide', 'Daily Traditional Coffee Ceremony', 'Domestic Flights Arrangement'],
    excluded: ['International Airfare', 'Personal Tips'],
    itinerary: [
      { dayNumber: 1, title: 'Flight Arrival in Lalibela & Northwestern Cluster', description: 'Arrive at Lalibela Airport. Afternoon exploration of Bet Medhane Alem and Bet Maryam churches.', mealsIncluded: ['Dinner'], accommodation: 'Mezena Lodge Lalibela' },
      { dayNumber: 2, title: 'Bet Giyorgis (St. George) & Southeastern Church Group', description: 'Early morning chanter prayers. Visit the famously carved cross-shaped Bet Giyorgis and subterranean rock tunnels.', mealsIncluded: ['Breakfast', 'Lunch', 'Dinner'], accommodation: 'Mezena Lodge Lalibela' },
      { dayNumber: 3, title: 'Asheten Maryam Mountain Monastery Hike', description: 'Option of mule ride or trek up Mount Asheten for panoramic sunset views over Lasta mountains.', mealsIncluded: ['Breakfast', 'Lunch', 'Dinner'], accommodation: 'Mezena Lodge Lalibela' },
      { dayNumber: 4, title: 'Traditional Honey Wine (Tej) Tasting & Departure', description: 'Sample local Tej and enjoy an authentic habesha cultural dance performance prior to flight departure.', mealsIncluded: ['Breakfast'], accommodation: 'N/A' },
    ],
    isFeatured: true,
    status: 'active',
  },
  {
    id: 'tour-103',
    title: 'Simien Mountains Roof of Africa Gelada Baboon Trek',
    slug: 'simien-mountains-gelada-baboon-trek',
    category: 'mountain',
    destination: DESTINATIONS[2],
    pricePerPerson: 980,
    durationDays: 5,
    maxGroupSize: 12,
    difficulty: 'challenging',
    rating: 4.95,
    reviewCount: 184,
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=1000',
    galleryImages: [
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&q=80&w=1000',
    ],
    summary: 'Trek along dramatic mountain precipices to observe hundreds of friendly endemic Gelada baboons, endangered Walia Ibex, and Ethiopian wolves in their alpine habitat.',
    included: ['Highland Tented Campsite & Lodge', 'Armed Wildlife Scout & Park Ranger', 'Camping Gear & Professional Trekking Chef', '4WD Mountain Support Vehicles', 'Park Entry & Wildlife Fees'],
    excluded: ['Trekking Boots', 'Personal Sleeping Bags'],
    itinerary: [
      { dayNumber: 1, title: 'Gonder to Debark Park HQ & Sankaber Camp', description: 'Drive from historic Gonder to Debark for park permits. First evening trek among Gelada baboon troops at Sankaber.', mealsIncluded: ['Lunch', 'Dinner'], accommodation: 'Sankaber Alpine Camp' },
      { dayNumber: 2, title: 'Jinbar Waterfall Gorge & Geech Plateau Trek', description: 'Hike past the 500m Jinbar Waterfall cliff and ascend through giant lobelia plants to Geech plateau.', mealsIncluded: ['Breakfast', 'Lunch', 'Dinner'], accommodation: 'Geech Campsite' },
      { dayNumber: 3, title: 'Imet Gogo Pinnacle Sunset Vantage Point', description: 'Reach 3,926m altitude for 360-degree views of serrated mountain peaks and spot Walia Ibex.', mealsIncluded: ['Breakfast', 'Lunch', 'Dinner'], accommodation: 'Limalimo Lodge' },
      { dayNumber: 4, title: 'Chennek Ridge Wildlife Safari & Ras Dashen View', description: 'Explore high pass paths where endemic Ethiopian wolves hunt giant mole-rats.', mealsIncluded: ['Breakfast', 'Lunch', 'Dinner'], accommodation: 'Limalimo Lodge' },
      { dayNumber: 5, title: 'Return Drive to Gonder Royal Castles & Airport', description: 'Morning breakfast before scenic descend to Gonder Fasil Ghebbi royal castle grounds.', mealsIncluded: ['Breakfast'], accommodation: 'N/A' },
    ],
    isFeatured: true,
    status: 'active',
  },
  {
    id: 'tour-104',
    title: 'Danakil Depression & Erta Ale Active Lava Lake Expedition',
    slug: 'danakil-depression-erta-ale-expedition',
    category: 'safari',
    destination: DESTINATIONS[3],
    pricePerPerson: 1250,
    durationDays: 4,
    maxGroupSize: 14,
    difficulty: 'challenging',
    rating: 4.97,
    reviewCount: 260,
    imageUrl: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&q=80&w=1000',
    galleryImages: [
      'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&q=80&w=1000',
    ],
    summary: 'Embark on an otherworldly journey to Dallol hydrothermal neon salt formations, trek up Erta Ale volcano to view glowing lava at night, and witness salt miner camel caravans.',
    included: ['Air-Conditioned 4x4 Land Cruisers', 'Volcano Night Trek Armed Guard Escort', 'Dallol Salt Hydrothermal Field Passports', 'Afar Local Expedition Lead', 'Unlimited Mineral Water Supply'],
    excluded: ['Extreme Weather Gear'],
    itinerary: [
      { dayNumber: 1, title: 'Semera/Mekelle Drive to Hamed Ela Base Camp', description: 'Traverse the salt pan desert of Afar, arriving at Hamed Ela in time for sunset over Lake Assal salt lake.', mealsIncluded: ['Dinner'], accommodation: 'Hamed Ela Open-Air Star Camp' },
      { dayNumber: 2, title: 'Dallol Neon Sulphur Springs & Salt Camel Caravans', description: 'Explore the vibrant yellow, green, and turquoise geothermal spring pools and observe traditional salt carving.', mealsIncluded: ['Breakfast', 'Lunch', 'Dinner'], accommodation: 'Hamed Ela Open-Air Star Camp' },
      { dayNumber: 3, title: 'Erta Ale Volcano Ascent & Night Lava Rim View', description: 'Late afternoon drive to Dodom base camp followed by 3-hour night trek up Erta Ale active basaltic volcano crater.', mealsIncluded: ['Breakfast', 'Lunch', 'Dinner'], accommodation: 'Erta Ale Summit Hut' },
      { dayNumber: 4, title: 'Sunrise Crater View & Transfer to Airport', description: 'Descend Erta Ale at dawn before 4x4 transfer back to Semera Airport for evening flight.', mealsIncluded: ['Breakfast', 'Lunch'], accommodation: 'N/A' },
    ],
    isFeatured: true,
    status: 'active',
    hasOffer: true,
    discountPercent: 20,
    originalPrice: 1560,
    offerTag: 'EARLY BIRD 20% DISCOUNT',
  },
  {
    id: 'tour-105',
    title: 'Bale Mountains Ethiopian Wolf & Sanetti Alpine Safari',
    slug: 'bale-mountains-ethiopian-wolf-safari',
    category: 'safari',
    destination: DESTINATIONS[4],
    pricePerPerson: 780,
    durationDays: 4,
    maxGroupSize: 10,
    difficulty: 'moderate',
    rating: 4.93,
    reviewCount: 145,
    imageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&q=80&w=1000',
    galleryImages: [
      'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&q=80&w=1000',
    ],
    summary: 'Spot the world’s rarest canid—the Ethiopian wolf—across the high Sanetti Plateau, explore Harenna cloud forest canopy, and visit Sof Omar limestone caves.',
    included: ['Bale Mountain Lodge Accommodation', 'Sanetti Plateau Safari Drive', 'Endemic Wolf Tracking Specialist', 'Harenna Forest Coffee Experience'],
    excluded: ['Personal Expenses'],
    itinerary: [
      { dayNumber: 1, title: 'Drive to Dinsho Park HQ & Mountain Nyala Sightings', description: 'Arrive at Dinsho HQ to spot endemic Mountain Nyala and Menelik Bushbuck grazers.', mealsIncluded: ['Lunch', 'Dinner'], accommodation: 'Bale Mountain Lodge' },
      { dayNumber: 2, title: 'Sanetti Plateau Ethiopian Wolf Tracking & Tullu Demtu', description: 'Ascend Africa’s highest all-weather road (4,000m+) to track packs of red Ethiopian wolves.', mealsIncluded: ['Breakfast', 'Lunch', 'Dinner'], accommodation: 'Bale Mountain Lodge' },
      { dayNumber: 3, title: 'Harenna Cloud Forest & Wild Coffee Harvest', description: 'Descend into lush moss-draped cloud forest trees to sample wild organic rainforest coffee.', mealsIncluded: ['Breakfast', 'Lunch', 'Dinner'], accommodation: 'Bale Mountain Lodge' },
      { dayNumber: 4, title: 'Sof Omar Caves Exploration & Return to Addis', description: 'Visit the spectacular 15km natural underground limestone cave system before return journey.', mealsIncluded: ['Breakfast', 'Lunch'], accommodation: 'N/A' },
    ],
    isFeatured: false,
    status: 'active',
  },
  {
    id: 'tour-106',
    title: 'Harar Jugol Walled Historic City & Wild Hyena Experience',
    slug: 'harar-jugol-historic-city-hyena-experience',
    category: 'cultural',
    destination: DESTINATIONS[5],
    pricePerPerson: 550,
    durationDays: 3,
    maxGroupSize: 12,
    difficulty: 'easy',
    rating: 4.94,
    reviewCount: 168,
    imageUrl: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&q=80&w=1000',
    galleryImages: [
      'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&q=80&w=1000',
    ],
    summary: 'Wander the 368 colorful alleyways of Harar Jugol walled city, visit Arthur Rimbaud museum, sample Harari spice markets, and witness the thrilling wild hyena man feeding ritual.',
    included: ['Heritage Guesthouse inside Jugol City', 'Hyena Feeding Evening Show Pass', 'Guided Alleyway & Mosque Heritage Walk', 'Harar Specialty Coffee Tasting'],
    excluded: ['Flights to Dire Dawa'],
    itinerary: [
      { dayNumber: 1, title: 'Dire Dawa Flight & Drive to Harar Jugol', description: 'Flight to Dire Dawa, short drive to Harar. Evening walk through 5 historic city gates.', mealsIncluded: ['Dinner'], accommodation: 'Harar Heritage Cultural House' },
      { dayNumber: 2, title: 'Rimbaud Cultural House, Spice Markets & Hyena Man Show', description: 'Visit historic museums and markets. At nightfall, witness the legendary Hyena Man feed wild spotted hyenas by hand.', mealsIncluded: ['Breakfast', 'Lunch', 'Dinner'], accommodation: 'Harar Heritage Cultural House' },
      { dayNumber: 3, title: 'Dire Dawa Railway History Tour & Airport Return', description: 'Morning coffee roasting demonstration before Dire Dawa historic train station visit and flight back.', mealsIncluded: ['Breakfast'], accommodation: 'N/A' },
    ],
    isFeatured: false,
    status: 'active',
  },
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'bk-9001',
    bookingReference: 'MCH-BKG-8819',
    tourPackageId: 'tour-101',
    tourTitle: 'Wenchi Crater Lake Eco-Resort & Equestrian Expedition',
    destinationName: 'Wenchi Crater Lake, Oromia Region',
    traveler: {
      name: 'Eleanor Vance',
      email: 'eleanor.vance@example.com',
      phone: '+251 91 123 4567',
      nationality: 'Ethiopia / US',
      specialRequests: 'Vegetarian meal plan requested for Day 2 boat tour.',
    },
    travelDate: '2026-09-15',
    numberOfTravelers: 2,
    numberOfAdults: 2,
    numberOfChildren: 0,
    totalPrice: 900,
    status: 'confirmed',
    paymentStatus: 'paid',
    bookingDate: '2026-08-01',
    assignedGuideId: 'gd-1',
    assignedGuideName: 'Abebe Bekele',
    refundStatus: 'none',
  },
  {
    id: 'bk-9002',
    bookingReference: 'MCH-BKG-4412',
    tourPackageId: 'tour-102',
    tourTitle: 'Lalibela World Heritage Monolithic Rock Churches Pilgrimage',
    destinationName: 'Lalibela Rock Churches, Amhara Region',
    traveler: {
      name: 'Liam Hemsworth',
      email: 'liam.h@example.co.uk',
      phone: '+44 20 7946 0912',
      nationality: 'United Kingdom',
      specialRequests: 'Wheelchair accessible transport required.',
    },
    travelDate: '2026-10-01',
    numberOfTravelers: 3,
    numberOfAdults: 2,
    numberOfChildren: 1,
    totalPrice: 2550,
    status: 'pending',
    paymentStatus: 'partial',
    bookingDate: '2026-08-05',
    assignedGuideId: 'gd-2',
    assignedGuideName: 'Tigist Haile',
    refundStatus: 'none',
  },
  {
    id: 'bk-9003',
    bookingReference: 'MCH-BKG-7721',
    tourPackageId: 'tour-104',
    tourTitle: 'Danakil Depression & Erta Ale Active Lava Lake Expedition',
    destinationName: 'Danakil Depression & Erta Ale, Afar Region',
    traveler: {
      name: 'Sophia Rossi',
      email: 'sophia.r@example.it',
      phone: '+39 06 6987 1234',
      nationality: 'Italy',
    },
    travelDate: '2026-08-28',
    numberOfTravelers: 2,
    numberOfAdults: 2,
    numberOfChildren: 0,
    totalPrice: 2500,
    status: 'paid',
    paymentStatus: 'paid',
    bookingDate: '2026-08-08',
    assignedGuideId: 'gd-3',
    assignedGuideName: 'Mohammed Ahmed',
    refundStatus: 'none',
  },
  {
    id: 'bk-9004',
    bookingReference: 'MCH-BKG-5533',
    tourPackageId: 'tour-103',
    tourTitle: 'Simien Mountains Gelada Baboon Trek & Ras Dashen Summit',
    destinationName: 'Simien Mountains, Amhara Region',
    traveler: {
      name: 'James Okonkwo',
      email: 'j.okonkwo@example.ng',
      phone: '+234 803 456 7890',
      nationality: 'Nigeria',
      specialRequests: 'Altitude sickness medication required on Day 3.',
    },
    travelDate: '2026-09-05',
    numberOfTravelers: 4,
    numberOfAdults: 3,
    numberOfChildren: 1,
    totalPrice: 5200,
    status: 'cancelled',
    paymentStatus: 'refunded',
    bookingDate: '2026-07-28',
    assignedGuideId: 'gd-1',
    assignedGuideName: 'Abebe Bekele',
    cancellationReason: 'Medical emergency — traveler unable to travel.',
    refundStatus: 'processed',
  },
];


export const INITIAL_GUIDES: TourGuide[] = [
  {
    id: 'gd-1',
    name: 'Abebe Bekele',
    email: 'abebe.b@michuutours.et',
    phone: '+251 911 234 567',
    nationality: 'Ethiopian',
    bio: 'Senior Eco-Ranger & Trekking Lead with over 10 years experience guiding high-altitude expeditions and eco-resort trails across Oromia and Bale.',
    experienceYears: 10,
    tourFee: 120,
    languages: ['Amharic', 'Oromiffa', 'English'],
    rating: 4.98,
    toursGuidedCount: 215,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150',
    status: 'available',
    specializations: ['Wenchi Eco-Trekking', 'Bale Mountains Safari', 'Flora & Fauna'],
    assignedTourIds: ['tour-101'],
    certifications: [
      { id: 'cert-101', name: 'National Senior Tour Guide Badge', issuedBy: 'Ethiopian Tourism Authority', issueDate: '2020-01-15', expiryDate: '2028-01-15' },
      { id: 'cert-102', name: 'Wilderness First Responder (WFR)', issuedBy: 'Red Cross International', issueDate: '2023-05-10', expiryDate: '2026-05-10' },
      { id: 'cert-103', name: 'High-Altitude Equestrian Safety', issuedBy: 'Oromia Eco-Tourism Alliance', issueDate: '2022-09-01', expiryDate: '2027-09-01' },
    ],
    availability: [
      { date: '2026-08-15', isAvailable: true, note: 'Wenchi Day Tour Slot' },
      { date: '2026-08-16', isAvailable: true },
      { date: '2026-08-20', isAvailable: false, note: 'Maintenance & Off-Duty' },
    ],
    paymentHistory: [
      { id: 'pay-1', tourTitle: 'Wenchi Crater Lake Eco-Resort', bookingReference: 'MCH-BKG-8819', date: '2026-08-02', amount: 450, status: 'paid' },
      { id: 'pay-2', tourTitle: 'Bale Mountains Summit Trek', bookingReference: 'MCH-BKG-3301', date: '2026-07-20', amount: 600, status: 'paid' },
    ],
  },
  {
    id: 'gd-2',
    name: 'Tigist Haile',
    email: 'tigist.h@michuutours.et',
    phone: '+251 912 345 678',
    nationality: 'Ethiopian',
    bio: 'Specialist in UNESCO World Heritage Monolithic Rock Churches, ancient Ge’ez manuscripts, and Orthodox church history in Lalibela.',
    experienceYears: 8,
    tourFee: 110,
    languages: ['Amharic', 'English', 'French'],
    rating: 4.96,
    toursGuidedCount: 180,
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=150',
    status: 'on_tour',
    specializations: ['UNESCO Lalibela Heritage', 'Orthodox Church History', 'Coffee Ceremonies'],
    assignedTourIds: ['tour-102'],
    certifications: [
      { id: 'cert-201', name: 'UNESCO World Heritage Interpreter', issuedBy: 'Ministry of Culture & Tourism', issueDate: '2021-03-01', expiryDate: '2029-03-01' },
      { id: 'cert-202', name: 'Advanced French Tourism License', issuedBy: 'Alliance Française', issueDate: '2019-11-12', expiryDate: '2027-11-12' },
    ],
    availability: [
      { date: '2026-08-14', isAvailable: false, note: 'Lalibela Pilgrimage Group' },
      { date: '2026-08-15', isAvailable: false, note: 'Lalibela Pilgrimage Group' },
      { date: '2026-08-18', isAvailable: true },
    ],
    paymentHistory: [
      { id: 'pay-3', tourTitle: 'Lalibela Monolithic Rock Churches', bookingReference: 'MCH-BKG-4412', date: '2026-08-06', amount: 550, status: 'pending' },
    ],
  },
  {
    id: 'gd-3',
    name: 'Mohammed Ahmed',
    email: 'mohammed.a@michuutours.et',
    phone: '+251 913 456 789',
    nationality: 'Ethiopian',
    bio: 'Expert Danakil Depression expedition leader & desert survival master. Specialist in active lava lakes, Dallol geothermal fields, and Afar salt caravans.',
    experienceYears: 12,
    tourFee: 150,
    languages: ['Afar', 'Amharic', 'English'],
    rating: 4.97,
    toursGuidedCount: 240,
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=150',
    status: 'available',
    specializations: ['Danakil & Erta Ale Volcano Lead', 'Desert Survival', 'Afar Cultural Heritage'],
    assignedTourIds: ['tour-104'],
    certifications: [
      { id: 'cert-301', name: 'Extreme Climate & Volcanic Survival Guide', issuedBy: 'Afar Regional Safety Bureau', issueDate: '2018-02-14', expiryDate: '2028-02-14' },
      { id: 'cert-302', name: 'Paramedic & Emergency Rescue', issuedBy: 'Afar Disaster Mgmt Agency', issueDate: '2022-01-20', expiryDate: '2027-01-20' },
    ],
    availability: [
      { date: '2026-08-28', isAvailable: false, note: 'Erta Ale Expedition' },
      { date: '2026-08-29', isAvailable: false, note: 'Erta Ale Expedition' },
      { date: '2026-09-01', isAvailable: true },
    ],
    paymentHistory: [
      { id: 'pay-4', tourTitle: 'Danakil & Erta Ale Lava Lake', bookingReference: 'MCH-BKG-7721', date: '2026-08-09', amount: 750, status: 'paid' },
    ],
  },
];
