export enum CorporateRole {
  CORPORATE_ADMIN = 'CORPORATE_ADMIN',
  TRAVEL_MANAGER = 'TRAVEL_MANAGER',
  APPROVER = 'APPROVER',
  TRAVELER = 'TRAVELER',
}

export enum RequestStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
}

export enum TravelClass {
  ECONOMY = 'ECONOMY',
  BUSINESS = 'BUSINESS',
  FIRST = 'FIRST',
}

export enum ApprovalDecision {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  ESCALATED = 'ESCALATED',
  SKIPPED = 'SKIPPED',
}

export enum ApproverType {
  SPECIFIC_USER = 'SPECIFIC_USER',
  ROLE = 'ROLE',
  DEPARTMENT_MANAGER = 'DEPARTMENT_MANAGER',
  COMPANY_ADMIN = 'COMPANY_ADMIN',
}
